# Copyright (c) IPRist Development Team
# Distributed under the terms of the Modified BSD License.
version: "3"

volumes:
  es01_data: {}
  redis_data: {}

services:
  notebook:
    build:
      context: ../notebook/notebook
      dockerfile: Dockerfile
    restart: always
    user: "jovyan:users"
    volumes:
      - ./data:/home/jovyan/data
      - ./images:/home/jovyan/images
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_PORT=10001
    ports:
      - "10001:10001"
    networks:
      - iprist-workspace-network

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es01_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - iprist-workspace-network

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--port", "6380"]
    ports:
      - "6380:6380"
    networks:
      - iprist-workspace-network

networks:
  iprist-workspace-network:
    driver: bridge
